permalink: /:categories/:title.html
url: "http://ecaepp.github.io/jekyll-masonry/"
full_name: "Patrick Peace"
first_name: "Patrick"
last_name: "Peace"
blog_title: "Huskurity "
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "ecaepp"
copyright_year: "2018"
google_analytics_code: ""
aboutme: "Something about the author here"
twitter: "Patrick51peace"
github: "ecaepp"
facebook: ""
linkined_url: "https://www.linkedin.com/in/patrickpeace/"
